name = "trade-worker"
account_id = "profile"
main = "src/index.js"
compatibility_date = "2024-03-26"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
D1_WORKER_URL = "https://d1-worker.cryptolinx.workers.dev"

# Secrets to be added with wrangler:
# wrangler secret put INTERNAL_SERVICE_KEY
# wrangler secret put MEXC_API_KEY
# wrangler secret put MEXC_API_SECRET
# wrangler secret put BINANCE_API_KEY
# wrangler secret put BINANCE_API_SECRET
# wrangler secret put BYBIT_API_KEY
# wrangler secret put BYBIT_API_SECRET
